Repository Comfy-Org/desktop, pull requests merged in 2024-12, with the labels that each got.

#418 v0.3.24
  package.json
Labels: Release

#432 Update to 0.3.25 (Types)
  package.json
Labels: ReleaseTypes

#437 v0.3.26
  package.json
Labels: Release

#441 v0.3.28
  package.json
Labels: Release

#448 v0.3.29
  package.json
Labels: Release

#452 Update frontend: 1.5.9
  package.json
Labels: dependencies

#454 v0.3.30
  package.json
Labels: Release

#459 [chore] Update frontend to 1.5.10
  package.json
Labels: dependencies

#462 v0.3.31
  package.json
Labels: Release

#475 [chore] Update frontend to 1.5.14
  package.json
Labels: dependencies

#476 v0.3.33
  package.json
Labels: Release

#495 0.3.34(types)
  package.json
Labels: ReleaseTypes

#532 [chore] Update frontend to 1.6.1
  package.json
Labels: dependencies

#535 v0.3.35
  package.json
Labels: Release

#546 v0.4.1
  package.json
Labels: Release

#548 v0.4.2
  package.json
Labels: Release

#557 0.4.3(types)
  package.json
Labels: ReleaseTypes

#566 [chore] Update frontend to 1.6.6
  package.json
Labels: dependencies

#581 v0.4.6 (types)
  package.json
Labels: ReleaseTypes
