Repository Comfy-Org/desktop, pull requests merged in 2025-08, with the labels that each got.

#1240 Update ComfyUI core to v0.3.48
  assets/requirements/macos.compiled
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/core-requirements.patch
Labels: ReleaseTypes, dependencies, size:S

#1242 v0.4.60
  package.json
Labels: Release, size:XS

#1245 v0.4.61
  package.json
Labels: Release, size:XS

#1258 Update ComfyUI core to v0.3.51
  assets/requirements/macos.compiled
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/core-requirements.patch
  tests/integration/install/installApp.spec.ts-snapshots/installApp-install-win32.png
Labels: ReleaseTypes, dependencies, size:S, lgtm

#1279 Update desktop to v0.4.67 and ComfyUI to v0.3.34
  package.json
Labels: Release, size:XS
