Repository Comfy-Org/desktop, pull requests merged in 2025-07, with the labels that each got.

#1219 v0.4.55: Bump ComfyUI + templates for moonvalley.
  assets/requirements/macos.compiled
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/core-remove-frontend.patch
  scripts/core-requirements.patch
Labels: dependencies, size:M

#1223 v0.4.56
  package.json
Labels: Release, size:XS

#1232 Update ComfyUI to v0.3.46
  assets/requirements/macos.compiled
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/core-requirements.patch
Labels: dependencies, size:S

#1236 Add macos.compiled to claude code command.
  .claude/commands/bump-stable.md
Labels: enhancement, size:XS

#1237 Update ComfyUI core to v0.3.47
  package.json
Labels: dependencies, size:XS, lgtm

#1238 v0.4.59
  package.json
Labels: Release, size:XS, lgtm
