Repository Comfy-Org/desktop, pull requests merged in 2025-03, with the labels that each got.

#912 Use upstream Manager.
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/makeComfy.js
  src/services/cmCli.ts
  src/virtualEnvironment.ts
Labels: size:M, lgtm

#1005 v0.4.24
  package.json
Labels: Release, size:XS

#1003 [e2e] Add update test expectations procedure
  package.json
  tests/README.md
Labels: documentation, size:S, lgtm

#1007 comfyui frontend v1.10.17
  package.json
  tests/integration/post-install/troubleshootingServerStart.spec.ts-snapshots/cannot-start-server-troubleshoot-cards-post-install-win32.png
Labels: dependencies, size:XS

#1008 v0.4.25
  package.json
Labels: Release, size:XS

#1009 Increase size limit for ToDesktop uploads.
  todesktop.json
Labels: size:XS

#1011 v0.4.26
  package.json
Labels: size:XS

#1015 Frontend v1.10.18
  package.json
Labels: dependencies, size:XS

#1027 Update ComfyUI to v0.3.23
  package.json
Labels: dependencies, size:XS

#1028 v0.4.28
  package.json
Labels: size:XS

#1040 Update Manager commit.
  package.json
Labels: bug, size:XS

#1039 Update ComfyUI to v0.3.26
  package.json
  scripts/core-remove-frontend.patch
  scripts/core-requirements.patch
Labels: dependencies, size:M, lgtm

#1041 v0.4.29
  package.json
Labels: size:XS

#1048 Update ComfyUI Manager
  package.json
Labels: bug, size:XS

#1034 Update Frontend v1.11.8
  package.json
  tests/integration/install/installApp.spec.ts-snapshots/installApp-install-win32.png
Labels: bug, size:XS

#1044 Use ComfyUI branch with commit for ignoring FE pip package.
  package.json
  scripts/makeComfy.js
  scripts/patchComfyUI.js
Labels: dependencies, size:S, lgtm

#1050 v0.4.30
  package.json
Labels: size:XS

#1051 Remove patch step since make:assets already runs it.
  .github/actions/build/todesktop/action.yml
Labels: size:XS

#1055 Fixed: User gets stuck in Desktop Updating page when error occurs
  src/install/installationManager.ts
Labels: bug, dependencies, size:S, lgtm

#1056 Rotate main.log file to make it easier to debug user sessions.
  src/main-process/appWindow.ts
  src/main-process/comfyServer.ts
  src/main.ts
  src/utils.ts
Labels: enhancement, size:S

#1061 Remove duplicate Windows build CI.
  .github/workflows/debug_all.yml
  .github/workflows/debug_windows.yml
  .github/workflows/integration_test_windows.yml
Labels: size:M

#1060 Check if directory is empty before installation warning.
  src/handlers/pathHandlers.ts
  tests/unit/handlers/pathHandler.test.ts
Labels: enhancement, size:M, lgtm

#1059 Install Path Validation Improvements
  src/handlers/pathHandlers.ts
  src/preload.ts
  tests/unit/handlers/pathHandler.test.ts
Labels: size:L, lgtm

#1067 [API] Publish types for version 0.4.31
  package.json
Labels: ReleaseTypes, size:XS

#1066 Check response of shell.openPath for errors.
  src/handlers/pathHandlers.ts
Labels: bug, size:S

#1070 update frontend to v1.14.5
  package.json
  tests/integration/install/installApp.spec.ts
  tests/integration/install/installApp.spec.ts-snapshots/installApp-install-win32.png
  tests/integration/install/installWizard.spec.ts-snapshots/choose-installation-location-install-win32.png
  tests/integration/post-install.setup.ts
  tests/integration/testInstalledApp.ts
Labels: dependencies, size:S

#1071 Update ComfyUI to v0.3.27
  package.json
Labels: dependencies, size:XS

#1072 Remove core branch.
  package.json
Labels: size:XS

#1073 Update patch to update requirements.
  scripts/core-requirements.patch
Labels: dependencies, size:XS

#1074 v0.4.32
  package.json
Labels: size:XS

#1080 Add support for loading vue devtools extension
  .env_example
  src/main.ts
Labels: enhancement, size:S, lgtm
