Repository Comfy-Org/desktop, pull requests merged in 2025-05, with the labels that each got.

#1134 Add toasts for update check
  package.json
  src/handlers/AppHandlers.ts
  src/preload.ts
  tests/unit/handlers/AppHandlers.test.ts
Labels: enhancement, ReleaseTypes, size:M

#1138 Update ComfyUI 0.3.31 + frontend 1.18.6
  package.json
  scripts/core-requirements.patch
  tests/integration/install/installApp.spec.ts-snapshots/installApp-install-win32.png
Labels: dependencies, size:XS

#1139 v0.4.44
  package.json
Labels: size:XS

#1148 Add docs link.
  README.md
Labels: documentation, size:XS

#1147 API node dependencies.
  package.json
  scripts/core-requirements.patch
Labels: dependencies, size:XS

#1153 Update logos.
  assets/UI/Comfy_Logo_x128.png
  assets/UI/Comfy_Logo_x16_BW.png
  assets/UI/Comfy_Logo_x32.png
Labels: size:XS

#1154 Change tray logo to BW.
  src/main-process/appWindow.ts
Labels: size:XS

#1162 API key release.
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/core-requirements.patch
  tests/integration/install/installApp.spec.ts-snapshots/installApp-install-win32.png
Labels: size:S

#1159 Update app icons
  assets/UI/Comfy_Icon_Windows.png
  assets/UI/Comfy_Logo_x1024.png
  assets/UI/Comfy_Logo_x256.png
  assets/UI/Comfy_Logo_x512.png
  todesktop.json
Labels: size:XS

#1163 v0.4.48
  package.json
Labels: Release, size:XS

#1169 v0.4.49
  package.json
Labels: Release, size:XS

#1177 Bump comfyUI version to support additional API nodes.
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  scripts/core-requirements.patch
  tests/integration/install/installApp.spec.ts-snapshots/installApp-install-win32.png
Labels: dependencies, size:S

#1178 v0.4.50
  package.json
Labels: size:XS
