Repository Comfy-Org/desktop, pull requests merged in 2025-02, with the labels that each got.

#804 Fixed: missing mock for unit test on MacOS.
  .gitattributes
  .github/workflows/ci.yaml
  tests/unit/main-process/appWindow.test.ts
Labels: bug, size:XS

#782 Use --base-directory in ComfyUI to resolve model import issues.
  src/config/comfyServerConfig.ts
  src/main-process/comfyServer.ts
  tests/unit/comfyServer.test.ts
  tests/unit/comfyServerConfig.test.ts
Labels: size:M

#829 Add tracking for python mirror urls.
  src/install/installationManager.ts
  src/services/telemetry.ts
  tests/unit/telemetry.test.ts
Labels: size:M

#828 Use global uv cache.
  src/virtualEnvironment.ts
Labels: size:XS

#838 Empty telemetry from front of the queue.
  src/services/telemetry.ts
  tests/unit/telemetry.test.ts
Labels: size:XS, lgtm

#837 Update Manager commit
  package.json
Labels: dependencies, size:XS

#835 uv 0.5.26
  package.json
Labels: size:XS

#842 Revert ComfyUI-Manager version.
  package.json
Labels: dependencies, size:XS

#843 ComfyUI v0.3.14
  package.json
Labels: enhancement, size:XS

#845 [chore] Update frontend to 1.9.6
  package.json
Labels: dependencies, size:XS

#846 Add telemetry for installation events (from validation page).
  src/install/installationManager.ts
Labels: enhancement, size:S

#847 v0.4.17
  package.json
Labels: size:XS

#848 Change window init logic to always place window at 0,0 at start
  src/main-process/appWindow.ts
Labels: enhancement, size:XS

#857 Update compiled requirements with new manager dependencies.
  README.md
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
Labels: dependencies, size:L

#872 Update compiled requirements for Windows.
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
Labels: size:L

#885 Add todesktop custom updater url.
  src/main-process/comfyDesktopApp.ts
  tests/unit/main-process/comfyDesktopApp.test.ts
  todesktop.json
Labels: size:XS, lgtm

#886 Update todesktop cli version for auto updater features.
  package.json
  yarn.lock
Labels: dependencies, size:XS, lgtm

#893 [chore] Update frontend to 1.9.15
  package.json
Labels: dependencies, size:XS

#889 Only use managed python for uv.
  src/virtualEnvironment.ts
Labels: size:XS

#911 Add support for bundling cherry-picked branches in Build Process
  package.json
  scripts/makeComfy.js
  vite.base.config.ts
Labels: Release, size:S

#962 Cherry-pick branch: Normalize paths in extra_model_paths
  package.json
Labels: size:XS

#996 Install expected missing pip dependencies + update ComfyUI v0.3.16
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  package.json
  src/install/installationManager.ts
  src/main-process/comfyInstallation.ts
  src/preload.ts
  src/virtualEnvironment.ts
Labels: dependencies, size:M

#998 v0.4.21
  package.json
Labels: size:XS

#999 Update ComfyUI to v0.3.17
  package.json
Labels: dependencies, size:XS

#1001 Update ComfyUI to v0.3.18
  package.json
Labels: dependencies, size:XS

#1002 v0.4.23
  package.json
Labels: size:XS
