Repository Comfy-Org/desktop, pull requests merged in 2025-01, with the labels that each got.

#590 Update package: systeminformation - uses full PowerShell path
  package.json
  src/shell/util.ts
  yarn.lock
Labels: dependencies

#597 0.4.7(types)
  package.json
Labels: ReleaseTypes

#598 [chore] Update frontend to 1.7.8
  package.json
Labels: dependencies

#627 0.4.8(types)
  package.json
Labels: ReleaseTypes

#646 [chore] Upgrade typescript-eslint to v8
  package.json
  yarn.lock
Labels: dependencies

#659 0.4.9(types)
  package.json
Labels: ReleaseTypes

#665 0.4.10(types)
  package.json
  yarn.lock
Labels: ReleaseTypes

#666 [chore] Update frontend to 1.7.14
  package.json
Labels: dependencies

#668 0.4.11(types)
  package.json
Labels: ReleaseTypes

#682 [Test] Add comfySettings unit tests
  tests/unit/comfySettings.test.ts
Labels: size:M, lgtm

#676 [Test] Add validate-install-path handler tests
  tests/unit/handlers/pathHandler.test.ts
Labels: lgtm

#678 [Test] Add vadlidateHardware unit tests
  .github/workflows/integration_test_windows.yml
  src/utils.ts
  tests/unit/utils.test.ts
Labels: lgtm

#679 [Test] Add ComfyServerConfig unit tests
  tests/assets/extra_models_paths/legacy-format.yaml
  tests/assets/extra_models_paths/malformed.yaml
  tests/assets/extra_models_paths/missing-base-path.yaml
  tests/assets/extra_models_paths/multiple-sections.yaml
  tests/assets/extra_models_paths/valid-config.yaml
  tests/assets/extra_models_paths/wrong-type.yaml
  tests/unit/comfyServerConfig.test.ts
Labels: lgtm

#690 Fixed: Quit app on mac when windows are closed.
  src/main.ts
Labels: bug, size:XS, lgtm

#697 Mark readonly fields as readonly
  src/main-process/appWindow.ts
  src/models/DownloadManager.ts
  src/services/cmCli.ts
  src/services/telemetry.ts
  src/shell/terminal.ts
  src/store/desktopConfig.ts
Labels: enhancement, size:M, lgtm

#691 [Test] Add unit tests for 100% coverage of comfyServerConfig
  tests/unit/comfyServerConfig.test.ts
Labels: size:M, lgtm

#692 [Test] Add unit tests for 100% coverage of comfySettings
  tests/unit/comfySettings.test.ts
Labels: size:S, lgtm

#693 [Test] Add unit tests for 100% coverage of comfyConfigManager
  tests/unit/comfyConfigManager.test.ts
Labels: size:S, lgtm

#694 [Test] Add unit tests for 100% coverage of pathHandlers
  tests/unit/handlers/pathHandler.test.ts
Labels: size:L, lgtm

#700 [chore] Update frontend to 1.8.4
  package.json
Labels: dependencies, size:XS

#695 Fix floating promises
  src/main-process/appWindow.ts
  src/main-process/comfyDesktopApp.ts
Labels: size:S, lgtm

#689 Track quitting and virtual env skip events.
  src/main.ts
  src/virtualEnvironment.ts
Labels: enhancement, size:S

#703 v0.4.13
  package.json
Labels: size:XS

#702 Update ESLint rules
  eslint.config.js
  tests/unit/comfySettings.test.ts
  tests/unit/telemetry.test.ts
  tests/unit/utils.test.ts
Labels: size:S, lgtm

#704 [Dev] Make auto open of DevTools optional
  .env_example
  src/main-process/appWindow.ts
Labels: enhancement, size:XS, lgtm

#705 Add telemetry for installation validation
  src/install/installationManager.ts
Labels: enhancement, size:XS, lgtm

#706 [Test] Add unit tests on handlers
  tests/unit/handlers/AppHandlers.test.ts
  tests/unit/handlers/appinfoHandlers.test.ts
Labels: size:L, lgtm

#712 [Test] Add install validation unit tests
  tests/unit/install/installationManager.test.ts
Labels: size:L, lgtm

#696 [Test] Add test on window close
  tests/integration/appLifecycle.spec.ts
Labels: size:S, lgtm

#713 Add UV mirror settings
  src/config/comfySettings.ts
  src/install/installWizard.ts
  src/main-process/comfyDesktopApp.ts
  src/main-process/comfyInstallation.ts
  src/preload.ts
  src/virtualEnvironment.ts
  tests/unit/comfySettings.test.ts
Labels: enhancement, size:M

#714 [BugFix] Don't set env var on empty mirror string
  src/virtualEnvironment.ts
Labels: bug, size:S

#711 Add electronAPI.Network.canAccessUrl
  src/constants.ts
  src/handlers/networkHandlers.ts
  src/main.ts
  src/preload.ts
  src/utils.ts
Labels: enhancement, size:M

#716 [Refactor] Remove unnecessary wrapper class on handlers
  src/handlers/AppHandlers.ts
  src/handlers/appInfoHandlers.ts
  src/handlers/networkHandlers.ts
  src/handlers/pathHandlers.ts
  src/main.ts
  tests/unit/handlers/AppHandlers.test.ts
  tests/unit/handlers/appinfoHandlers.test.ts
  tests/unit/handlers/pathHandler.test.ts
Labels: size:L, lgtm

#717 0.4.15(types)
  package.json
Labels: ReleaseTypes, size:XS

#730 Allow app to check the current browser location
  src/main-process/appWindow.ts
Labels: enhancement, size:S, lgtm

#729 [DevExperience] Add @/ root path syntax support
  scripts/resetInstall.js
  tests/unit/comfyConfigManager.test.ts
  tests/unit/comfyServer.test.ts
  tests/unit/comfyServerConfig.test.ts
  tests/unit/comfySettings.test.ts
  tests/unit/handlers/AppHandlers.test.ts
  tests/unit/handlers/appinfoHandlers.test.ts
  tests/unit/handlers/pathHandler.test.ts
  tests/unit/install/installationManager.test.ts
  tests/unit/store/desktopConfig.test.ts
  tests/unit/telemetry.test.ts
  tests/unit/utils.test.ts
  tsconfig.json
  vite.base.config.ts
Labels: enhancement, size:M, lgtm

#732 [Cleanup] Remove unnecessary lint-staged entry in package.json
  package.json
Labels: size:XS

#734 Use node v20 for macos builds
  .github/workflows/debug_macos.yml
  .github/workflows/publish_macos.yml
Labels: size:XS

#736 [Test] Remove unused test file
  tests/unit/main.test.ts
Labels: size:M, lgtm

#737 Remove virtual environment creation from server start
  src/install/installationManager.ts
  src/main-process/comfyDesktopApp.ts
Labels: size:L, lgtm

#738 [Refactor] Construct torch install args
  src/virtualEnvironment.ts
Labels: size:L, lgtm

#739 Add Sentry URL to mixpanel error events
  src/services/sentry.ts
  src/services/telemetry.ts
Labels: enhancement, size:M, lgtm

#741 [Cleanup] Remove unused API endpoint isFirstTimeSetup
  src/constants.ts
  src/main-process/comfyDesktopApp.ts
  src/preload.ts
Labels: size:S

#743 Support using custom torch pip mirror
  src/config/comfySettings.ts
  src/install/installWizard.ts
  src/main-process/comfyInstallation.ts
  src/preload.ts
  src/virtualEnvironment.ts
  tests/unit/comfySettings.test.ts
Labels: enhancement, size:S

#744 Change default torch to cuda 12.4
  assets/requirements/windows_nvidia.compiled
  src/virtualEnvironment.ts
Labels: size:L, lgtm

#751 Fix pypi mirror usage in virtualEnvironment.ts
  src/virtualEnvironment.ts
Labels: bug, size:M

#752 Extract hardcoded torch install URL to global constants
  src/constants.ts
  src/virtualEnvironment.ts
Labels: enhancement, size:XS

#753 0.4.16(types)
  package.json
Labels: ReleaseTypes, size:XS

#766 Add maintenance task logging
  src/install/installationManager.ts
  src/virtualEnvironment.ts
Labels: enhancement, size:S, lgtm

#767 Fix pip prerelease install
  src/virtualEnvironment.ts
Labels: bug, size:XS

#757 Use frontend configured torch index-url
  src/virtualEnvironment.ts
Labels: size:M

#768 [chore] Update frontend to 1.8.9
  package.json
  scripts/updateFrontend.js
Labels: dependencies, size:XS

#769 Allow 3xx status code in canAccessUrl check
  src/utils.ts
Labels: size:XS

#771 Update ComfyUI to v0.3.13
  package.json
Labels: dependencies, size:XS, lgtm

#773 Fix misaligned setting ids for UV mirrors
  src/config/comfySettings.ts
  src/install/installWizard.ts
Labels: size:S

#774 Revert "Fix misaligned setting ids for UV mirrors"
  src/config/comfySettings.ts
  src/install/installWizard.ts
Labels: size:S

#775 [Reland] Fix misaligned mirror setting ids
  src/config/comfySettings.ts
  src/install/installWizard.ts
  src/main-process/comfyInstallation.ts
  tests/unit/comfySettings.test.ts
Labels: bug, size:M

#776 Fallback to default torch mirror on default setting value
  src/virtualEnvironment.ts
Labels: enhancement, size:S

#778 [chore] Update frontend to 1.8.10
  package.json
Labels: dependencies, size:XS

#779 [chore] Update frontend to 1.8.11
  package.json
Labels: dependencies, size:XS

#790 [chore] Update frontend to 1.8.12
  package.json
  scripts/updateFrontend.js
Labels: dependencies, size:XS
