Repository Comfy-Org/desktop, pull requests merged in 2025-04, with the labels that each got.

#1085 Bump FE to 1.15.13
  package.json
Labels: dependencies, size:XS

#1086 Bump core 0.3.28
  package.json
  scripts/core-requirements.patch
Labels: dependencies, size:XS

#1087 v0.4.33
  package.json
Labels: size:XS

#1091 Add change to install templates.
  package.json
  scripts/core-requirements.patch
  src/virtualEnvironment.ts
Labels: size:S

#1093 v0.4.34
  package.json
Labels: size:XS

#1090 Support Blackwell GPUs
  src/constants.ts
  src/desktopApp.ts
  src/handlers/gpuHandlers.ts
  src/preload.ts
  tests/unit/handlers/gpuHandlers.test.ts
Labels: enhancement, ReleaseTypes, size:L, lgtm

#1098 0.4.36 (Types)
  package.json
Labels: ReleaseTypes, size:XS

#1100 Update wanfun templates.
  assets/requirements/windows_cpu.compiled
  assets/requirements/windows_nvidia.compiled
  scripts/core-requirements.patch
Labels: size:XS

#1099 Fix typo `extra_model_config` in README
  README.md
Labels: documentation, size:XS, lgtm

#1097 Add manual update check
  src/constants.ts
  src/handlers/AppHandlers.ts
  src/preload.ts
  tests/unit/handlers/AppHandlers.test.ts
Labels: enhancement, size:L

#1101 [API] Publish types for version 0.4.37
  package.json
Labels: ReleaseTypes, size:XS

#1102 Promise version in checkForUpdates
  package.json
  src/preload.ts
Labels: enhancement, ReleaseTypes, size:XS

#1103 Allow options to be passed to checkForUpdates
  package.json
  src/preload.ts
Labels: enhancement, ReleaseTypes, size:XS

#1128 Patched: Check user consent before incrementing property.
  src/services/telemetry.ts
Labels: size:XS

#1129 v0.4.41
  package.json
Labels: Release, size:XS

#1132 Update README.md
  README.md
Labels: documentation, size:XS
